# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Example-Swift-AKLM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example-Swift-AKLM
  pod 'AKLanguageManager', :path => '../'

  target 'Example-Swift-AKLMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Example-Swift-AKLMUITests' do
    # Pods for testing
  end

end
