name: main-CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs WIP Blocker
      - name: WIP Blocker
        uses: ParanoidBeing/action-wip-blocker@v0.1.1-rc

